package com.nook.service;
import com.nook.application.port.out.*; import com.nook.domain.SocialEntities.*; import com.nook.dto.ApiDtos.*; import com.nook.exception.ApiException; import com.nook.mapper.SocialMapper; import com.nook.repository.SocialRepository; import com.nook.security.JwtService; import jakarta.persistence.EntityManager; import jakarta.transaction.Transactional; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.security.authentication.BadCredentialsException; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.security.SecureRandom; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;
@Service public class AuthService { private final SocialRepository repo;private final PasswordEncoder encoder;private final JwtService jwt;private final SocialMapper mapper;private final EntityManager em;private final long refreshDays;private final ExternalIdentityVerifier identities;private final OtpProviderPort otpProvider;private final AuditService audit;private final SecureRandom random=new SecureRandom();public AuthService(SocialRepository r,PasswordEncoder e,JwtService j,SocialMapper m,EntityManager em,@Value("${nook.refresh-days}")long d,ExternalIdentityVerifier identities,OtpProviderPort otpProvider,AuditService audit){repo=r;encoder=e;jwt=j;mapper=m;this.em=em;refreshDays=d;this.identities=identities;this.otpProvider=otpProvider;this.audit=audit;}
 @Transactional public Token register(Register x){String email=x.email().trim().toLowerCase();if(repo.userByEmail(email).isPresent())throw new ApiException(HttpStatus.CONFLICT,"EMAIL_EXISTS","Ese email ya está registrado. Entra con tu contraseña.");User u=provisional(email,"Nuevo café");u.passwordHash=encoder.encode(x.password());AuthIdentity identity=new AuthIdentity();identity.userId=u.id;identity.provider=AuthProvider.EMAIL;identity.providerSubject=email;identity.email=email;repo.save(identity);return token(u);}
 @Transactional public Token login(Login x){User u=repo.userByEmail(x.email()).filter(v->v.active&&encoder.matches(x.password(),v.passwordHash)).orElseThrow(()->new BadCredentialsException("bad"));return token(u);}
 @Transactional public Token refresh(String raw){String h=hash(raw);RefreshToken t=em.createQuery("select t from SocialEntities$RefreshToken t where t.tokenHash=:h and t.revokedAt is null and t.expiresAt>:now",RefreshToken.class).setParameter("h",h).setParameter("now",Instant.now()).setLockMode(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE).getResultStream().findFirst().orElseThrow(()->new BadCredentialsException("bad"));t.revokedAt=Instant.now();User user=repo.user(t.userId);if(user==null||!user.active)throw new BadCredentialsException("bad");return token(user);}
 @Transactional public void logout(String raw){em.createQuery("update SocialEntities$RefreshToken t set t.revokedAt=:now where t.tokenHash=:h and t.revokedAt is null").setParameter("now",Instant.now()).setParameter("h",hash(raw)).executeUpdate();}
 @Transactional public Token federated(AuthProvider provider,FederatedAuth request){var verified=identities.verify(provider,request.identityToken());repo.lockAuthIdentityKey(provider,verified.subject());AuthIdentity identity=repo.identity(provider,verified.subject()).orElse(null);User user;if(identity!=null){user=repo.user(identity.userId);if(user==null||!user.active)throw new BadCredentialsException("bad");identity.lastLoginAt=Instant.now();}else{boolean reusableEmail=verified.emailVerified()&&verified.email()!=null&&!verified.email().isBlank();String email=reusableEmail?verified.email().trim().toLowerCase():provider.name().toLowerCase()+"-"+hash(verified.subject()).substring(0,20)+"@identity.nook.invalid";String name=Optional.ofNullable(request.displayName()).filter(s->!s.isBlank()).orElse(Optional.ofNullable(verified.displayName()).orElse("Nuevo café"));user=reusableEmail?repo.userByEmail(email).orElseGet(()->provisional(email,name)):provisional(email,name);if(!user.active)throw new BadCredentialsException("bad");identity=new AuthIdentity();identity.userId=user.id;identity.provider=provider;identity.providerSubject=verified.subject();identity.email=verified.email();repo.save(identity);}syncSocialPhoto(user.id,provider,verified.pictureUrl());audit.record(user.id,"LOGIN","USER",user.id);return token(user);}
 @Transactional public PhoneOtpRequested requestPhoneOtp(String phone){
  Instant now=Instant.now();
  repo.latestOtp(phone).ifPresent(previous->{
   if(previous.createdAt.isAfter(now.minusSeconds(30)))throw new ApiException(HttpStatus.TOO_MANY_REQUESTS,"OTP_RESEND_TOO_SOON","Espera 30 segundos antes de solicitar otro código");
   if(previous.consumedAt==null)previous.consumedAt=now;
  });
  String code=String.format("%06d",random.nextInt(1_000_000));
  PhoneOtpChallenge challenge=new PhoneOtpChallenge();challenge.phone=phone;challenge.codeHash=encoder.encode(code);challenge.expiresAt=now.plus(5,ChronoUnit.MINUTES);
  repo.save(challenge);otpProvider.send(phone,code);
  return new PhoneOtpRequested(challenge.id,300,otpProvider.exposesDevelopmentCode()?code:null);
 }
 @Transactional public Token verifyPhoneOtp(PhoneOtpVerify request){
  PhoneOtpChallenge challenge=repo.otp(request.challengeId()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"OTP_INVALID","El código ha caducado o no es válido"));
  repo.lock(challenge);
  if(challenge.consumedAt!=null||challenge.expiresAt.isBefore(Instant.now())||challenge.attempts>=5)throw new ApiException(HttpStatus.UNAUTHORIZED,"OTP_INVALID","El código ha caducado o no es válido");
  challenge.attempts++;
  if(!encoder.matches(request.code(),challenge.codeHash))throw new ApiException(HttpStatus.UNAUTHORIZED,"OTP_INVALID","El código no es válido");
  challenge.consumedAt=Instant.now();
  repo.lockAuthIdentityKey(AuthProvider.PHONE,challenge.phone);
  AuthIdentity identity=repo.identity(AuthProvider.PHONE,challenge.phone).orElse(null);User user;
  if(identity==null){String email="phone-"+hash(challenge.phone).substring(0,20)+"@identity.nook.invalid";user=provisional(email,"Nuevo café");identity=new AuthIdentity();identity.userId=user.id;identity.provider=AuthProvider.PHONE;identity.providerSubject=challenge.phone;identity.phone=challenge.phone;repo.save(identity);}else user=repo.user(identity.userId);
  if(user==null||!user.active)throw new BadCredentialsException("bad");
  identity.lastLoginAt=Instant.now();audit.record(user.id,"LOGIN","USER",user.id);return token(user);
 }
 private User provisional(String email,String name){User u=new User();u.email=email;u.passwordHash=encoder.encode(UUID.randomUUID().toString());repo.save(u);Profile p=new Profile();p.user=u;p.name=name;repo.save(p);Preference pref=new Preference();pref.user=u;repo.save(pref);em.flush();audit.record(u.id,"USER_CREATED","USER",u.id);return u;}
 private void syncSocialPhoto(UUID userId,AuthProvider provider,String url){if(url==null||url.isBlank())return;try{var uri=java.net.URI.create(url);if(!"https".equalsIgnoreCase(uri.getScheme())||uri.getHost()==null)return;}catch(IllegalArgumentException ignored){return;}Photo photo=repo.socialPhoto(userId,provider).orElseGet(()->{Photo value=new Photo();value.userId=userId;value.source="SOCIAL";value.provider=provider.name();value.position=100;value.primary=repo.photos(userId).isEmpty();repo.save(value);return value;});photo.url=url;}
 private Token token(User u){if(u==null||!u.active)throw new BadCredentialsException("bad");String raw=UUID.randomUUID()+"."+UUID.randomUUID();RefreshToken t=new RefreshToken();t.userId=u.id;t.tokenHash=hash(raw);t.expiresAt=Instant.now().plus(refreshDays,ChronoUnit.DAYS);repo.save(t);return new Token(jwt.issue(u.id),raw,"Bearer",jwt.expiresSeconds(),mapper.me(u));} private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
