package com.nook.service;
import com.nook.application.port.out.MediaStoragePort; import com.nook.domain.SocialEntities.*; import com.nook.dto.ApiDtos.*; import com.nook.exception.ApiException; import com.nook.mapper.SocialMapper; import com.nook.repository.SocialRepository; import jakarta.transaction.Transactional; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.time.*; import java.util.*;
@Service public class UserService { final SocialRepository repo;final SocialMapper mapper;final AuditService audit;final MediaStoragePort media;public UserService(SocialRepository r,SocialMapper m,AuditService audit,MediaStoragePort media){repo=r;mapper=m;this.audit=audit;this.media=media;} public Me me(UUID id){return mapper.me(requireUser(id));} User requireUser(UUID id){User u=repo.user(id);if(u==null||!u.active)throw new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","Usuario no encontrado");return u;}
 public DiscoverProfile profile(UUID viewer,UUID id){requireUser(viewer);requireUser(id);if(repo.blocked(viewer,id))throw new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","Usuario no encontrado");return mapper.profile(viewer,repo.profile(id));}
 @Transactional public UserSettingsDto settings(UUID id){requireUser(id);UserSetting value=repo.settings(id);if(value==null){value=new UserSetting();value.userId=id;repo.save(value);}return new UserSettingsDto(value.coffeeSoundsEnabled,value.pushEnabled,value.locale);}
 @Transactional public UserSettingsDto updateSettings(UUID id,UpdateUserSettings request){requireUser(id);UserSetting value=repo.settings(id);if(value==null){value=new UserSetting();value.userId=id;repo.save(value);}if(request.coffeeSoundsEnabled()!=null)value.coffeeSoundsEnabled=request.coffeeSoundsEnabled();if(request.pushEnabled()!=null)value.pushEnabled=request.pushEnabled();if(request.locale()!=null&&!request.locale().isBlank())value.locale=request.locale();value.updatedAt=Instant.now();return new UserSettingsDto(value.coffeeSoundsEnabled,value.pushEnabled,value.locale);}
 @Transactional public void updateLocation(UUID id,UpdateUserLocation request){requireUser(id);Instant now=Instant.now();if(request.capturedAt().isBefore(now.minusSeconds(300))||request.capturedAt().isAfter(now.plusSeconds(30)))throw new ApiException(HttpStatus.BAD_REQUEST,"STALE_LOCATION","La ubicación ya no es reciente");if(request.accuracyMeters()>1000)throw new ApiException(HttpStatus.BAD_REQUEST,"IMPRECISE_LOCATION","Necesitamos una ubicación aproximada válida");double latitude=Math.round(request.latitude()*1000d)/1000d,longitude=Math.round(request.longitude()*1000d)/1000d;UserLocation value=repo.location(id);boolean created=value==null;if(created){value=new UserLocation();value.userId=id;}value.latitude=latitude;value.longitude=longitude;value.accuracyMeters=request.accuracyMeters();value.capturedAt=request.capturedAt();value.updatedAt=now;if(created)repo.save(value);Profile profile=repo.profile(id);profile.latitude=latitude;profile.longitude=longitude;profile.updatedAt=now;}
 @Transactional public Me update(UUID id,UpdateMe x){User u=requireUser(id);Profile p=repo.profile(id);Preference f=repo.preference(id);if(x.birthDate()!=null){if(Period.between(x.birthDate(),LocalDate.now()).getYears()<18)throw new ApiException(HttpStatus.BAD_REQUEST,"UNDERAGE","Debes tener al menos 18 años");p.birthDate=x.birthDate();}if(x.name()!=null)p.name=x.name();if(x.gender()!=null)p.gender=x.gender();if(x.bio()!=null)p.bio=x.bio();if(x.city()!=null)p.city=x.city();if((x.latitude()==null)!=(x.longitude()==null))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_COORDINATES","Latitud y longitud deben enviarse juntas");if(x.latitude()!=null){if(!Double.isFinite(x.latitude())||!Double.isFinite(x.longitude())||x.latitude() < -90||x.latitude()>90||x.longitude() < -180||x.longitude()>180)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_COORDINATES","Coordenadas no válidas");p.latitude=x.latitude();p.longitude=x.longitude();}if(x.lookingFor()!=null)p.lookingFor=x.lookingFor();if(x.coffeePersonality()!=null)p.coffeePersonality=x.coffeePersonality();if(x.preferredPlan()!=null)p.preferredPlan=x.preferredPlan();if(x.preferredVibe()!=null)p.preferredVibe=x.preferredVibe();if(x.coffeesPerDay()!=null)p.coffeesPerDay=x.coffeesPerDay();if(x.favoriteCoffeeMoment()!=null)p.favoriteCoffeeMoment=x.favoriteCoffeeMoment();if(x.onboardingComplete()!=null)p.onboardingComplete=x.onboardingComplete();if(x.minAge()!=null)f.minAge=x.minAge();if(x.maxAge()!=null)f.maxAge=x.maxAge();if(f.maxAge<f.minAge)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_AGE_RANGE","Rango de edad inválido");if(x.maxDistanceKm()!=null)f.maxDistanceKm=x.maxDistanceKm();if(x.visible()!=null)f.visible=x.visible();if(x.hidden()!=null)u.hidden=x.hidden();if(x.desiredGenders()!=null)f.desiredGenders=join(x.desiredGenders());if(x.discoveryIntentions()!=null)f.intentions=join(x.discoveryIntentions());if(x.discoveryVibes()!=null)f.preferredVibes=join(x.discoveryVibes());if(x.discoveryMoments()!=null)f.preferredMoments=join(x.discoveryMoments());if(x.discoveryMeetingStyles()!=null)f.meetingStyles=join(x.discoveryMeetingStyles());p.updatedAt=u.updatedAt=Instant.now();if(x.coffeePreferences()!=null)repo.replaceCoffees(id,x.coffeePreferences());audit.record(id,"PROFILE_UPDATED","USER",id);return mapper.me(u);}
 private String join(List<String> values){return values.stream().map(String::trim).filter(v->!v.isBlank()).distinct().limit(20).collect(java.util.stream.Collectors.joining(","));}
 @Transactional public PhotoDto uploadPhoto(UUID id,MultipartFile file){User user=requireUser(id);repo.lock(user);List<Photo> photos=repo.userPhotos(id);ensurePhotoCapacity(photos);if(file.isEmpty()||file.getSize()>8_000_000)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_PHOTO","La foto debe pesar menos de 8 MB");String content=Optional.ofNullable(file.getContentType()).orElse("");if(!content.equals("image/jpeg")&&!content.equals("image/png")&&!content.equals("image/heic")&&!content.equals("image/heif"))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_PHOTO_TYPE","Usa una imagen JPG, PNG, HEIC o HEIF");Photo p=new Photo();p.userId=id;p.source="USER";p.position=photos.size();p.primary=photos.isEmpty();try{p.url=media.storeUserPhoto(UUID.randomUUID(),file.getInputStream(),content).publicUrl();}catch(IOException e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_PHOTO","No se pudo leer la foto");}repo.save(p);return mapper.photo(p);}
 public MediaStoragePort.StoredContent photoContent(String filename){return media.resolveUserPhoto(filename);}
 @Transactional public void removePhoto(UUID user,UUID photo){User owner=requireUser(user);repo.lock(owner);Photo p=repo.find(Photo.class,photo);if(p==null||!p.userId.equals(user))throw new ApiException(HttpStatus.NOT_FOUND,"PHOTO_NOT_FOUND","Foto no encontrada");boolean wasPrimary=p.primary;media.deleteUserPhoto(p.url);repo.remove(p);repo.flush();if(wasPrimary){List<Photo> remaining=repo.photos(user);if(!remaining.isEmpty()){repo.setPrimaryPhoto(user,remaining.get(0).id);remaining.get(0).primary=true;}}}
 @Transactional public List<PhotoDto> reorderPhotos(UUID user,List<UUID> ids){User owner=requireUser(user);repo.lock(owner);List<Photo> photos=repo.photos(user);Set<UUID> expected=photos.stream().map(p->p.id).collect(java.util.stream.Collectors.toSet());if(ids.size()!=photos.size()||!new HashSet<>(ids).equals(expected))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_PHOTO_ORDER","El orden debe contener todas tus fotos una sola vez");Map<UUID,Photo> byId=photos.stream().collect(java.util.stream.Collectors.toMap(p->p.id,p->p));for(int i=0;i<ids.size();i++)byId.get(ids.get(i)).position=i+100;repo.flush();for(int i=0;i<ids.size();i++)byId.get(ids.get(i)).position=i;repo.flush();return ids.stream().map(id->mapper.photo(byId.get(id))).toList();}
 @Transactional public PhotoDto makePrimary(UUID user,UUID id){User owner=requireUser(user);repo.lock(owner);List<Photo> photos=repo.photos(user);Photo selected=photos.stream().filter(p->p.id.equals(id)).findFirst().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"PHOTO_NOT_FOUND","Foto no encontrada"));repo.clearPrimaryPhoto(user);repo.setPrimaryPhoto(user,id);selected.primary=true;return mapper.photo(selected);}
 private void ensurePhotoCapacity(List<Photo> photos){if(photos.size()>=8)throw new ApiException(HttpStatus.CONFLICT,"PHOTO_LIMIT","Puedes tener hasta 8 fotos");}
 @Transactional public void block(UUID me,UUID other){if(me.equals(other))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_BLOCK","No puedes bloquearte a ti mismo");repo.lockUsers(me,other);requireUser(other);if(!repo.blocked(me,other)){Block b=new Block();b.blockerId=me;b.blockedId=other;repo.save(b);}repo.match(me,other).ifPresent(m->m.active=false);repo.cancelActiveDatesBetween(me,other);audit.record(me,"BLOCK","USER",other);}
 @Transactional public void report(UUID me,UUID other,ReportRequest x){if(me.equals(other))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_REPORT","No puedes reportarte a ti mismo");requireUser(other);Report r=new Report();r.reporterId=me;r.reportedId=other;r.reason=x.reason();r.details=x.details();repo.save(r);audit.record(me,"REPORT","USER",other);}
 @Transactional public void deleteAccount(UUID id){User u=requireUser(id);u.active=false;u.hidden=true;u.updatedAt=Instant.now();}
}
