package com.nook.domain;

import jakarta.persistence.*;
import java.time.*;
import java.util.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

public final class SocialEntities {
 private SocialEntities() {}
 public enum Gender { WOMAN,MAN,NON_BINARY,OTHER }
 public enum LookingFor { CASUAL_COFFEE,SOMETHING_MORE,PROJECT,FRIENDSHIP,SUPPORT,OPEN_ENDED,MEET_PEOPLE,SEE_WHAT_HAPPENS }
 public enum DateStatus { PENDING,ACCEPTED,DECLINED,COUNTER_PROPOSED,CANCELLED,COMPLETED,EXPIRED }
 public enum PaymentPreference { I_INVITE,THEY_INVITE,SPLIT,DECIDE_THERE }
 public enum AuthProvider { APPLE,GOOGLE,FACEBOOK,PHONE,EMAIL }

 @MappedSuperclass public abstract static class Base { @Id @GeneratedValue(strategy=GenerationType.UUID) public UUID id; @Column(name="created_at",nullable=false) public Instant createdAt=Instant.now(); }
 @Entity @Table(name="users") public static class User extends Base { @Column(unique=true) public String email; @Column(unique=true) public String phone; @Column(name="password_hash") public String passwordHash; public boolean active=true; public boolean hidden=false; @Column(name="updated_at",nullable=false) public Instant updatedAt=Instant.now(); }
 @Entity @Table(name="auth_identities") public static class AuthIdentity extends Base { @Column(name="user_id",nullable=false) public UUID userId; @Enumerated(EnumType.STRING) @Column(nullable=false) public AuthProvider provider; @Column(name="provider_subject",nullable=false) public String providerSubject; public String email; public String phone; @Column(name="last_login_at") public Instant lastLoginAt=Instant.now(); }
 @Entity @Table(name="phone_otp_challenges") public static class PhoneOtpChallenge extends Base { @Column(nullable=false) public String phone; @Column(name="code_hash") public String codeHash; @Column(name="provider_reference") public String providerReference; public short attempts; @Column(name="expires_at",nullable=false) public Instant expiresAt; @Column(name="consumed_at") public Instant consumedAt; }
 @Entity @Table(name="user_profiles") public static class Profile { @Id @Column(name="user_id") public UUID userId; @OneToOne(fetch=FetchType.LAZY) @MapsId @JoinColumn(name="user_id") public User user; @Column(nullable=false) public String name; @Column(name="birth_date") public LocalDate birthDate; @Enumerated(EnumType.STRING) public Gender gender; @Column(nullable=false) public String bio=""; public String city; public Double latitude; public Double longitude; @Enumerated(EnumType.STRING) @Column(name="looking_for") public LookingFor lookingFor; @Column(name="coffee_personality") public String coffeePersonality; @Column(name="preferred_plan") public String preferredPlan; @Column(name="preferred_vibe") public String preferredVibe; @Column(name="coffees_per_day") public Integer coffeesPerDay; @Column(name="favorite_coffee_moment") public String favoriteCoffeeMoment; @Column(name="onboarding_complete") public boolean onboardingComplete; @Column(name="onboarding_step") public int onboardingStep; @Column(name="updated_at") public Instant updatedAt=Instant.now(); }
 @Entity @Table(name="user_preferences") public static class Preference { @Id @Column(name="user_id") public UUID userId; @OneToOne(fetch=FetchType.LAZY) @MapsId @JoinColumn(name="user_id") public User user; @Column(name="min_age") public int minAge=18; @Column(name="max_age") public int maxAge=45; @Column(name="max_distance_km") public int maxDistanceKm=30; public boolean visible=true; @Column(name="desired_genders") public String desiredGenders; public String intentions; @Column(name="coffee_types") public String coffeeTypes; @Column(name="preferred_vibes") public String preferredVibes; @Column(name="preferred_moments") public String preferredMoments; @Column(name="meeting_styles") public String meetingStyles; }
 @Entity @Table(name="user_settings") public static class UserSetting { @Id @Column(name="user_id") public UUID userId; @Version public long version; @Column(name="coffee_sounds_enabled") public boolean coffeeSoundsEnabled=true; @Column(name="push_enabled") public boolean pushEnabled=true; public String locale="es"; @Column(name="updated_at") public Instant updatedAt=Instant.now(); }
 @Entity @Table(name="user_locations") public static class UserLocation { @Id @Column(name="user_id") public UUID userId; public double latitude; public double longitude; @Column(name="accuracy_meters") public Double accuracyMeters; @Column(name="captured_at") public Instant capturedAt; @Column(name="updated_at") public Instant updatedAt=Instant.now(); }
 @Entity @Table(name="user_photos") public static class Photo extends Base { @Column(name="user_id",nullable=false) public UUID userId; @Column(nullable=false) public String url; public int position; @Column(name="is_primary") public boolean primary; @Column(nullable=false) public String source="USER"; public String provider; }
 @Entity @Table(name="coffee_preferences") @IdClass(CoffeePreferenceId.class) public static class CoffeePreference { @Id @Column(name="user_id") public UUID userId; @Id public String preference; }
 public static class CoffeePreferenceId implements java.io.Serializable { public UUID userId; public String preference; public CoffeePreferenceId(){} public CoffeePreferenceId(UUID u,String p){userId=u;preference=p;} @Override public boolean equals(Object value){return value instanceof CoffeePreferenceId other&&Objects.equals(userId,other.userId)&&Objects.equals(preference,other.preference);}@Override public int hashCode(){return Objects.hash(userId,preference);} }
 @Entity @Table(name="coffee_likes") public static class CoffeeLike extends Base { @Column(name="sender_id",nullable=false) public UUID senderId; @Column(name="receiver_id",nullable=false) public UUID receiverId; }
 @Entity @Table(name="passes") public static class UserPass extends Base { @Column(name="sender_id",nullable=false) public UUID senderId; @Column(name="receiver_id",nullable=false) public UUID receiverId; }
 @Entity @Table(name="matches") public static class Match extends Base { @Column(name="user_one_id",nullable=false) public UUID userOneId; @Column(name="user_two_id",nullable=false) public UUID userTwoId; public boolean active=true; @Column(name="updated_at") public Instant updatedAt=Instant.now(); }
 @Entity @Table(name="conversations") public static class Conversation extends Base { @Column(name="match_id",nullable=false,unique=true) public UUID matchId; @Column(name="updated_at") public Instant updatedAt=Instant.now(); }
 @Entity @Table(name="messages") public static class Message extends Base { @Column(name="conversation_id",nullable=false) public UUID conversationId; @Column(name="sender_id") public UUID senderId; @Column(name="client_message_id") public UUID clientMessageId; @Column(nullable=false) public String body; @Column(name="message_type") public String messageType="TEXT"; @JdbcTypeCode(SqlTypes.JSON) @Column(columnDefinition="jsonb") public String metadata; @Column(name="read_at") public Instant readAt; }
 @Entity @Table(name="coffee_shops") public static class CoffeeShop extends Base { public String provider="SEED"; @Column(name="provider_id") public String providerId; @Column(nullable=false) public String name; @Column(nullable=false) public String address; public String neighborhood; public double latitude; public double longitude; @Column(name="photo_url") public String photoUrl; @Transient public List<String> photoUrls=List.of(); @Transient public String category; @Column(name="opening_hours") public String openingHours; @Column(columnDefinition="numeric(2,1)") public Double rating; @Column(name="review_count") public Integer reviewCount; @Column(name="open_now") public Boolean openNow; @Column(name="price_level") public String priceLevel; public String website; public String phone; @Column(name="maps_url") public String mapsUrl; @Column(columnDefinition="text") public String types; public String description; public boolean active=true; @Column(name="updated_at") public Instant updatedAt=Instant.now(); }
 @Entity @Table(name="coffee_shop_vibes") @IdClass(VibeId.class) public static class CoffeeShopVibe { @Id @Column(name="coffee_shop_id") public UUID coffeeShopId; @Id public String vibe; }
 public static class VibeId implements java.io.Serializable { public UUID coffeeShopId; public String vibe; public VibeId(){} @Override public boolean equals(Object value){return value instanceof VibeId other&&Objects.equals(coffeeShopId,other.coffeeShopId)&&Objects.equals(vibe,other.vibe);}@Override public int hashCode(){return Objects.hash(coffeeShopId,vibe);} }
 @Entity @Table(name="coffee_date_proposals") public static class CoffeeDateProposal extends Base { @Column(name="sender_id") public UUID senderId; @Column(name="receiver_id") public UUID receiverId; @Column(name="match_id") public UUID matchId; @Column(name="coffee_shop_id") public UUID coffeeShopId; @Column(name="idempotency_key") public UUID idempotencyKey; @JdbcTypeCode(SqlTypes.JSON) @Column(name="coffee_shop_snapshot",columnDefinition="jsonb") public String coffeeShopSnapshot; @Column(name="nook_choice",nullable=false) public boolean nookChoice; @Column(name="proposed_at") public Instant proposedAt; @Enumerated(EnumType.STRING) @Column(name="payment_preference") public PaymentPreference paymentPreference; @Enumerated(EnumType.STRING) public DateStatus status=DateStatus.PENDING; @Column(name="updated_at") public Instant updatedAt=Instant.now(); @Column(name="accepted_at") public Instant acceptedAt; @Column(name="completed_at") public Instant completedAt; }
 @Entity @Table(name="blocks") public static class Block extends Base { @Column(name="blocker_id") public UUID blockerId; @Column(name="blocked_id") public UUID blockedId; }
 @Entity @Table(name="reports") public static class Report extends Base { @Column(name="reporter_id") public UUID reporterId; @Column(name="reported_id") public UUID reportedId; public String reason; public String details; }
 @Entity @Table(name="notifications") public static class Notification extends Base { @Column(name="user_id") public UUID userId; public String type; public String title; public String body; @Column(name="resource_id") public UUID resourceId; @Column(name="read_at") public Instant readAt; }
 @Entity @Table(name="refresh_tokens") public static class RefreshToken extends Base { @Column(name="user_id") public UUID userId; @Column(name="token_hash",unique=true) public String tokenHash; @Column(name="expires_at") public Instant expiresAt; @Column(name="revoked_at") public Instant revokedAt; }
 @Entity @Table(name="device_tokens") public static class DeviceToken extends Base { @Column(name="user_id") public UUID userId; @Column(unique=true) public String token; public String platform="IOS"; @Column(name="updated_at") public Instant updatedAt=Instant.now(); }
 @Entity @Table(name="audit_events") public static class AuditEvent extends Base { @Column(name="actor_user_id") public UUID actorUserId; @Column(name="event_type") public String eventType; @Column(name="resource_type") public String resourceType; @Column(name="resource_id") public UUID resourceId; @JdbcTypeCode(SqlTypes.JSON) @Column(columnDefinition="jsonb") public String metadata="{}"; }
}
