ALTER TYPE looking_for ADD VALUE IF NOT EXISTS 'CASUAL_COFFEE';
ALTER TYPE looking_for ADD VALUE IF NOT EXISTS 'PROJECT';
ALTER TYPE looking_for ADD VALUE IF NOT EXISTS 'SUPPORT';
ALTER TYPE looking_for ADD VALUE IF NOT EXISTS 'OPEN_ENDED';
