package com.nook.repository;
import com.nook.application.port.out.UserAccountStatusPort; import com.nook.domain.SocialEntities.*; import jakarta.persistence.*; import org.springframework.stereotype.Repository; import java.time.*; import java.util.*;
@Repository public class SocialRepository implements UserAccountStatusPort {
 @PersistenceContext EntityManager em;
 public <T> T save(T value){if(value instanceof Base b && b.id!=null)return em.merge(value);em.persist(value);return value;}
 public User user(UUID id){return em.find(User.class,id);} public Optional<User> userByEmail(String email){return em.createQuery("select u from SocialEntities$User u where lower(u.email)=lower(:e)",User.class).setParameter("e",email).getResultStream().findFirst();}
 @Override public boolean isActive(UUID id){User value=user(id);return value!=null&&value.active;}
 public Optional<AuthIdentity> identity(AuthProvider provider,String subject){return em.createQuery("select i from SocialEntities$AuthIdentity i where i.provider=:p and i.providerSubject=:s",AuthIdentity.class).setParameter("p",provider).setParameter("s",subject).getResultStream().findFirst();}
 public Optional<PhoneOtpChallenge> otp(UUID id){return Optional.ofNullable(em.find(PhoneOtpChallenge.class,id));}
 public Profile profile(UUID id){return em.find(Profile.class,id);} public Preference preference(UUID id){return em.find(Preference.class,id);}
 public UserSetting settings(UUID id){return em.find(UserSetting.class,id);}
 public UserLocation location(UUID id){return em.find(UserLocation.class,id);}
 public List<Photo> photos(UUID id){return em.createQuery("select p from SocialEntities$Photo p where p.userId=:u order by p.position",Photo.class).setParameter("u",id).getResultList();}
 public void clearPrimaryPhoto(UUID user){em.createQuery("update SocialEntities$Photo p set p.primary=false where p.userId=:u").setParameter("u",user).executeUpdate();}
 public void setPrimaryPhoto(UUID user,UUID id){em.createNativeQuery("update user_photos set is_primary=true where user_id=:u and id=:i").setParameter("u",user).setParameter("i",id).executeUpdate();}
 public List<String> coffees(UUID id){return em.createQuery("select c.preference from SocialEntities$CoffeePreference c where c.userId=:u",String.class).setParameter("u",id).getResultList();}
 public void replaceCoffees(UUID id,List<String> values){em.createQuery("delete from SocialEntities$CoffeePreference c where c.userId=:u").setParameter("u",id).executeUpdate(); for(String v:values){var c=new CoffeePreference();c.userId=id;c.preference=v;em.persist(c);}}
 public void remove(Object x){em.remove(x);} public <T> T find(Class<T> type,UUID id){return em.find(type,id);}
 public boolean likeExists(UUID a,UUID b){return !em.createQuery("select l.id from SocialEntities$CoffeeLike l where l.senderId=:a and l.receiverId=:b",UUID.class).setParameter("a",a).setParameter("b",b).setMaxResults(1).getResultList().isEmpty();}
 public boolean passExists(UUID a,UUID b){return !em.createQuery("select p.id from SocialEntities$UserPass p where p.senderId=:a and p.receiverId=:b",UUID.class).setParameter("a",a).setParameter("b",b).setMaxResults(1).getResultList().isEmpty();}
 public boolean blocked(UUID a,UUID b){return !em.createQuery("select x.id from SocialEntities$Block x where (x.blockerId=:a and x.blockedId=:b) or (x.blockerId=:b and x.blockedId=:a)",UUID.class).setParameter("a",a).setParameter("b",b).setMaxResults(1).getResultList().isEmpty();}
 public Optional<Match> match(UUID a,UUID b){UUID one=a.toString().compareTo(b.toString())<0?a:b,two=one.equals(a)?b:a;return em.createQuery("select m from SocialEntities$Match m where m.userOneId=:a and m.userTwoId=:b",Match.class).setParameter("a",one).setParameter("b",two).getResultStream().findFirst();}
 public List<Match> matches(UUID u){return em.createQuery("select m from SocialEntities$Match m where m.active=true and (m.userOneId=:u or m.userTwoId=:u) order by m.createdAt desc",Match.class).setParameter("u",u).getResultList();}
 public Conversation conversationByMatch(UUID id){return em.createQuery("select c from SocialEntities$Conversation c where c.matchId=:m",Conversation.class).setParameter("m",id).getSingleResult();}
 public boolean matchMember(UUID match,UUID user){return !em.createQuery("select m.id from SocialEntities$Match m where m.id=:m and m.active=true and (m.userOneId=:u or m.userTwoId=:u)",UUID.class).setParameter("m",match).setParameter("u",user).getResultList().isEmpty();}
 public boolean conversationMember(UUID conversation,UUID user){return !em.createQuery("select c.id from SocialEntities$Conversation c, SocialEntities$Match m where c.id=:c and c.matchId=m.id and m.active=true and (m.userOneId=:u or m.userTwoId=:u)",UUID.class).setParameter("c",conversation).setParameter("u",user).getResultList().isEmpty();}
 public List<Conversation> conversations(UUID u){return em.createQuery("select c from SocialEntities$Conversation c, SocialEntities$Match m where c.matchId=m.id and m.active=true and (m.userOneId=:u or m.userTwoId=:u) order by c.updatedAt desc",Conversation.class).setParameter("u",u).getResultList();}
 public List<Message> messages(UUID c,int page,int size){return em.createQuery("select m from SocialEntities$Message m where m.conversationId=:c order by m.createdAt desc",Message.class).setParameter("c",c).setFirstResult(page*size).setMaxResults(size).getResultList();}
 public Optional<Message> messageByClientId(UUID conversation,UUID clientId){return em.createQuery("select m from SocialEntities$Message m where m.conversationId=:c and m.clientMessageId=:i",Message.class).setParameter("c",conversation).setParameter("i",clientId).getResultStream().findFirst();}
 public List<CoffeeShop> shops(){return em.createQuery("select s from SocialEntities$CoffeeShop s where s.active=true",CoffeeShop.class).getResultList();} public List<String> vibes(UUID id){return em.createQuery("select v.vibe from SocialEntities$CoffeeShopVibe v where v.coffeeShopId=:s",String.class).setParameter("s",id).getResultList();}
 public boolean shopProviderExists(String providerId){return !em.createQuery("select s.id from SocialEntities$CoffeeShop s where s.providerId=:p",UUID.class).setParameter("p",providerId).setMaxResults(1).getResultList().isEmpty();}
 public Optional<CoffeeShop> shopByProviderId(String providerId){return em.createQuery("select s from SocialEntities$CoffeeShop s where s.providerId=:p",CoffeeShop.class).setParameter("p",providerId).getResultStream().findFirst();}
 public void deactivateSeedShops(){em.createQuery("update SocialEntities$CoffeeShop s set s.active=false where s.provider='SEED'").executeUpdate();}
 public List<CoffeeDateProposal> dates(UUID u){return em.createQuery("select d from SocialEntities$CoffeeDateProposal d where d.senderId=:u or d.receiverId=:u order by d.proposedAt",CoffeeDateProposal.class).setParameter("u",u).getResultList();}
 public List<CoffeeDateProposal> acceptedDatesBefore(Instant threshold){return em.createQuery("select d from SocialEntities$CoffeeDateProposal d where d.status=:status and d.proposedAt<:threshold",CoffeeDateProposal.class).setParameter("status",DateStatus.ACCEPTED).setParameter("threshold",threshold).getResultList();}
 public Optional<CoffeeDateProposal> activeDate(UUID match){return em.createQuery("select d from SocialEntities$CoffeeDateProposal d where d.matchId=:m and d.status in (:pending,:counter)",CoffeeDateProposal.class).setParameter("m",match).setParameter("pending",DateStatus.PENDING).setParameter("counter",DateStatus.COUNTER_PROPOSED).getResultStream().findFirst();}
 public Optional<CoffeeDateProposal> dateByIdempotencyKey(UUID sender,UUID key){return em.createQuery("select d from SocialEntities$CoffeeDateProposal d where d.senderId=:sender and d.idempotencyKey=:key",CoffeeDateProposal.class).setParameter("sender",sender).setParameter("key",key).getResultStream().findFirst();}
 public List<Notification> notifications(UUID u,int page,int size){return em.createQuery("select n from SocialEntities$Notification n where n.userId=:u order by n.createdAt desc",Notification.class).setParameter("u",u).setFirstResult(page*size).setMaxResults(size).getResultList();}
 public Optional<DeviceToken> deviceToken(String token){return em.createQuery("select d from SocialEntities$DeviceToken d where d.token=:t",DeviceToken.class).setParameter("t",token).getResultStream().findFirst();}
 public List<DeviceToken> deviceTokens(UUID user){return em.createQuery("select d from SocialEntities$DeviceToken d where d.userId=:u",DeviceToken.class).setParameter("u",user).getResultList();}
 public List<Profile> discover(UUID u,int min,int max){LocalDate today=LocalDate.now();LocalDate oldest=today.minusYears(max+1L).plusDays(1),newest=today.minusYears(min);return em.createQuery("select p from SocialEntities$Profile p join p.user x join SocialEntities$Preference pref on pref.userId=p.userId where p.userId<>:u and x.active=true and x.hidden=false and pref.visible=true and p.onboardingComplete=true and p.birthDate between :oldest and :newest and not exists(select b.id from SocialEntities$Block b where (b.blockerId=:u and b.blockedId=p.userId) or (b.blockerId=p.userId and b.blockedId=:u)) and not exists(select l.id from SocialEntities$CoffeeLike l where l.senderId=:u and l.receiverId=p.userId) and not exists(select ps.id from SocialEntities$UserPass ps where ps.senderId=:u and ps.receiverId=p.userId)",Profile.class).setParameter("u",u).setParameter("oldest",oldest).setParameter("newest",newest).setMaxResults(50).getResultList();}
 public void execute(String jpql,String name,Object value){em.createQuery(jpql).setParameter(name,value).executeUpdate();}
}
