package com.nook.repository;
import com.nook.application.port.out.UserAccountStatusPort; import com.nook.domain.SocialEntities.*; import jakarta.persistence.*; import org.springframework.stereotype.Repository; import java.time.*; import java.util.*;
@Repository public class SocialRepository implements UserAccountStatusPort {
 @PersistenceContext EntityManager em;
 public <T> T save(T value){if(value instanceof Base b && b.id!=null)return em.merge(value);em.persist(value);return value;}
 public User user(UUID id){return em.find(User.class,id);} public Optional<User> userByEmail(String email){return em.createQuery("select u from SocialEntities$User u where lower(u.email)=lower(:e)",User.class).setParameter("e",email).getResultStream().findFirst();}
 @Override public boolean isActive(UUID id){User value=user(id);return value!=null&&value.active;}
 public Optional<AuthIdentity> identity(AuthProvider provider,String subject){return em.createQuery("select i from SocialEntities$AuthIdentity i where i.provider=:p and i.providerSubject=:s",AuthIdentity.class).setParameter("p",provider).setParameter("s",subject).getResultStream().findFirst();}
 public void lockAuthIdentityKey(AuthProvider provider,String subject){em.createNativeQuery("select pg_advisory_xact_lock(hashtextextended(:identity,0))").setParameter("identity",provider.name()+":"+subject).getSingleResult();}
 public Optional<PhoneOtpChallenge> otp(UUID id){return Optional.ofNullable(em.find(PhoneOtpChallenge.class,id));}
 public Optional<PhoneOtpChallenge> latestOtp(String phone){return em.createQuery("select c from SocialEntities$PhoneOtpChallenge c where c.phone=:phone order by c.createdAt desc",PhoneOtpChallenge.class).setParameter("phone",phone).setMaxResults(1).getResultStream().findFirst();}
 public Profile profile(UUID id){return em.find(Profile.class,id);} public Preference preference(UUID id){return em.find(Preference.class,id);}
 public UserSetting settings(UUID id){return em.find(UserSetting.class,id);}
 public UserLocation location(UUID id){return em.find(UserLocation.class,id);}
 public List<Photo> photos(UUID id){return em.createQuery("select p from SocialEntities$Photo p where p.userId=:u and (p.source='USER' or not exists(select own.id from SocialEntities$Photo own where own.userId=:u and own.source='USER')) order by p.primary desc,p.position,p.createdAt",Photo.class).setParameter("u",id).getResultList();}
 public List<Photo> userPhotos(UUID id){return em.createQuery("select p from SocialEntities$Photo p where p.userId=:u and p.source='USER' order by p.primary desc,p.position",Photo.class).setParameter("u",id).getResultList();}
 public Optional<Photo> socialPhoto(UUID id,AuthProvider provider){return em.createQuery("select p from SocialEntities$Photo p where p.userId=:u and p.source='SOCIAL' and p.provider=:provider",Photo.class).setParameter("u",id).setParameter("provider",provider.name()).getResultStream().findFirst();}
 public void clearPrimaryPhoto(UUID user){em.createQuery("update SocialEntities$Photo p set p.primary=false where p.userId=:u").setParameter("u",user).executeUpdate();}
 public void setPrimaryPhoto(UUID user,UUID id){em.createNativeQuery("update user_photos set is_primary=true where user_id=:u and id=:i").setParameter("u",user).setParameter("i",id).executeUpdate();}
 public List<String> coffees(UUID id){return em.createQuery("select c.preference from SocialEntities$CoffeePreference c where c.userId=:u",String.class).setParameter("u",id).getResultList();}
 public void replaceCoffees(UUID id,List<String> values){em.createQuery("delete from SocialEntities$CoffeePreference c where c.userId=:u").setParameter("u",id).executeUpdate(); for(String v:values){var c=new CoffeePreference();c.userId=id;c.preference=v;em.persist(c);}}
 public void remove(Object x){em.remove(x);} public <T> T find(Class<T> type,UUID id){return em.find(type,id);}
 public void lock(Object value){em.lock(value,LockModeType.PESSIMISTIC_WRITE);}
 public void lockUsers(UUID first,UUID second){List<UUID> ids=new ArrayList<>(List.of(first,second));ids.sort(Comparator.comparing(UUID::toString));em.createQuery("select u from SocialEntities$User u where u.id in :ids order by u.id",User.class).setParameter("ids",ids).setLockMode(LockModeType.PESSIMISTIC_WRITE).getResultList();}
 public void flush(){em.flush();}
 public boolean likeExists(UUID a,UUID b){return !em.createQuery("select l.id from SocialEntities$CoffeeLike l where l.senderId=:a and l.receiverId=:b",UUID.class).setParameter("a",a).setParameter("b",b).setMaxResults(1).getResultList().isEmpty();}
 public boolean passExists(UUID a,UUID b){return !em.createQuery("select p.id from SocialEntities$UserPass p where p.senderId=:a and p.receiverId=:b",UUID.class).setParameter("a",a).setParameter("b",b).setMaxResults(1).getResultList().isEmpty();}
 public boolean blocked(UUID a,UUID b){return !em.createQuery("select x.id from SocialEntities$Block x where (x.blockerId=:a and x.blockedId=:b) or (x.blockerId=:b and x.blockedId=:a)",UUID.class).setParameter("a",a).setParameter("b",b).setMaxResults(1).getResultList().isEmpty();}
 public Optional<Match> match(UUID a,UUID b){UUID one=a.toString().compareTo(b.toString())<0?a:b,two=one.equals(a)?b:a;return em.createQuery("select m from SocialEntities$Match m where m.userOneId=:a and m.userTwoId=:b",Match.class).setParameter("a",one).setParameter("b",two).getResultStream().findFirst();}
 public List<Match> matches(UUID u){return em.createQuery("select m from SocialEntities$Match m where m.active=true and (m.userOneId=:u or m.userTwoId=:u) order by m.createdAt desc",Match.class).setParameter("u",u).getResultList();}
 public Conversation conversationByMatch(UUID id){return em.createQuery("select c from SocialEntities$Conversation c where c.matchId=:m",Conversation.class).setParameter("m",id).getSingleResult();}
 public boolean matchMember(UUID match,UUID user){return !em.createQuery("select m.id from SocialEntities$Match m where m.id=:m and m.active=true and (m.userOneId=:u or m.userTwoId=:u)",UUID.class).setParameter("m",match).setParameter("u",user).getResultList().isEmpty();}
 public boolean conversationMember(UUID conversation,UUID user){return !em.createQuery("select c.id from SocialEntities$Conversation c, SocialEntities$Match m where c.id=:c and c.matchId=m.id and m.active=true and (m.userOneId=:u or m.userTwoId=:u)",UUID.class).setParameter("c",conversation).setParameter("u",user).getResultList().isEmpty();}
 public List<Conversation> conversations(UUID u){return em.createQuery("select c from SocialEntities$Conversation c, SocialEntities$Match m where c.matchId=m.id and m.active=true and (m.userOneId=:u or m.userTwoId=:u) order by c.updatedAt desc",Conversation.class).setParameter("u",u).getResultList();}
 public List<Message> messages(UUID c,int page,int size){return em.createQuery("select m from SocialEntities$Message m where m.conversationId=:c order by m.createdAt desc",Message.class).setParameter("c",c).setFirstResult(page*size).setMaxResults(size).getResultList();}
 public Optional<Message> messageByClientId(UUID conversation,UUID clientId){return em.createQuery("select m from SocialEntities$Message m where m.conversationId=:c and m.clientMessageId=:i",Message.class).setParameter("c",conversation).setParameter("i",clientId).getResultStream().findFirst();}
 public List<CoffeeShop> shops(){return em.createQuery("select s from SocialEntities$CoffeeShop s where s.active=true",CoffeeShop.class).getResultList();} public List<String> vibes(UUID id){return em.createQuery("select v.vibe from SocialEntities$CoffeeShopVibe v where v.coffeeShopId=:s",String.class).setParameter("s",id).getResultList();}
 public Map<UUID,CoffeeShop> shopsByIds(Set<UUID> ids){if(ids.isEmpty())return Map.of();Map<UUID,CoffeeShop> result=new HashMap<>();em.createQuery("select s from SocialEntities$CoffeeShop s where s.id in :ids",CoffeeShop.class).setParameter("ids",ids).getResultList().forEach(s->result.put(s.id,s));return result;}
 public Map<UUID,List<String>> vibesByShopIds(Set<UUID> ids){if(ids.isEmpty())return Map.of();Map<UUID,List<String>> result=new HashMap<>();for(Object[] row:em.createQuery("select v.coffeeShopId,v.vibe from SocialEntities$CoffeeShopVibe v where v.coffeeShopId in :ids",Object[].class).setParameter("ids",ids).getResultList())result.computeIfAbsent((UUID)row[0],ignored->new ArrayList<>()).add((String)row[1]);return result;}
 public boolean shopProviderExists(String providerId){return !em.createQuery("select s.id from SocialEntities$CoffeeShop s where s.providerId=:p",UUID.class).setParameter("p",providerId).setMaxResults(1).getResultList().isEmpty();}
 public Optional<CoffeeShop> shopByProviderId(String providerId){return em.createQuery("select s from SocialEntities$CoffeeShop s where s.providerId=:p",CoffeeShop.class).setParameter("p",providerId).getResultStream().findFirst();}
 public void deactivateSeedShops(){em.createQuery("update SocialEntities$CoffeeShop s set s.active=false where s.provider='SEED'").executeUpdate();}
 public List<CoffeeDateProposal> dates(UUID u){return em.createQuery("select d from SocialEntities$CoffeeDateProposal d where (d.senderId=:u or d.receiverId=:u) and not exists(select b.id from SocialEntities$Block b where (b.blockerId=d.senderId and b.blockedId=d.receiverId) or (b.blockerId=d.receiverId and b.blockedId=d.senderId)) order by d.proposedAt",CoffeeDateProposal.class).setParameter("u",u).getResultList();}
 public void cancelActiveDatesBetween(UUID a,UUID b){em.createQuery("update SocialEntities$CoffeeDateProposal d set d.status=:cancelled,d.updatedAt=:now where ((d.senderId=:a and d.receiverId=:b) or (d.senderId=:b and d.receiverId=:a)) and d.status in (:pending,:counter)").setParameter("cancelled",DateStatus.CANCELLED).setParameter("now",Instant.now()).setParameter("a",a).setParameter("b",b).setParameter("pending",DateStatus.PENDING).setParameter("counter",DateStatus.COUNTER_PROPOSED).executeUpdate();}
 public void cancelOngoingDatesForMatch(UUID match){em.createQuery("update SocialEntities$CoffeeDateProposal d set d.status=:cancelled,d.updatedAt=:now where d.matchId=:match and d.status in (:pending,:counter,:accepted)").setParameter("cancelled",DateStatus.CANCELLED).setParameter("now",Instant.now()).setParameter("match",match).setParameter("pending",DateStatus.PENDING).setParameter("counter",DateStatus.COUNTER_PROPOSED).setParameter("accepted",DateStatus.ACCEPTED).executeUpdate();}
 public List<CoffeeDateProposal> acceptedDatesBefore(Instant threshold){return em.createQuery("select d from SocialEntities$CoffeeDateProposal d where d.status=:status and d.proposedAt<:threshold",CoffeeDateProposal.class).setParameter("status",DateStatus.ACCEPTED).setParameter("threshold",threshold).getResultList();}
 public List<CoffeeDateProposal> pendingDatesBefore(Instant threshold){return em.createQuery("select d from SocialEntities$CoffeeDateProposal d where d.status in (:pending,:counter) and d.proposedAt<:threshold",CoffeeDateProposal.class).setParameter("pending",DateStatus.PENDING).setParameter("counter",DateStatus.COUNTER_PROPOSED).setParameter("threshold",threshold).getResultList();}
 public Optional<CoffeeDateProposal> activeDate(UUID match){return em.createQuery("select d from SocialEntities$CoffeeDateProposal d where d.matchId=:m and d.status in (:pending,:counter,:accepted)",CoffeeDateProposal.class).setParameter("m",match).setParameter("pending",DateStatus.PENDING).setParameter("counter",DateStatus.COUNTER_PROPOSED).setParameter("accepted",DateStatus.ACCEPTED).getResultStream().findFirst();}
 public Optional<CoffeeDateProposal> dateByIdempotencyKey(UUID sender,UUID key){return em.createQuery("select d from SocialEntities$CoffeeDateProposal d where d.senderId=:sender and d.idempotencyKey=:key",CoffeeDateProposal.class).setParameter("sender",sender).setParameter("key",key).getResultStream().findFirst();}
 public void setDateTimeZone(UUID proposal,String timeZoneId){em.createNativeQuery("update coffee_date_proposals set time_zone_id=:zone where id=:id").setParameter("zone",timeZoneId).setParameter("id",proposal).executeUpdate();}
 public String dateTimeZone(UUID proposal){Object value=em.createNativeQuery("select time_zone_id from coffee_date_proposals where id=:id").setParameter("id",proposal).getSingleResult();return String.valueOf(value);}
 public Map<UUID,String> dateTimeZones(Set<UUID> proposals){
  if(proposals.isEmpty())return Map.of();
  Map<UUID,String> result=new HashMap<>();
  List<?> rows=em.createNativeQuery("select id,time_zone_id from coffee_date_proposals where id in (:ids)").setParameter("ids",proposals).getResultList();
  for(Object value:rows){Object[] row=(Object[])value;result.put((UUID)row[0],String.valueOf(row[1]));}
  return result;
 }
 public List<Notification> notifications(UUID u,int page,int size){return em.createQuery("select n from SocialEntities$Notification n where n.userId=:u order by n.createdAt desc",Notification.class).setParameter("u",u).setFirstResult(page*size).setMaxResults(size).getResultList();}
 public Optional<DeviceToken> deviceToken(String token){return em.createQuery("select d from SocialEntities$DeviceToken d where d.token=:t",DeviceToken.class).setParameter("t",token).getResultStream().findFirst();}
 public List<DeviceToken> deviceTokens(UUID user){return em.createQuery("select d from SocialEntities$DeviceToken d where d.userId=:u",DeviceToken.class).setParameter("u",user).getResultList();}
 public List<Profile> discover(UUID u,int min,int max){LocalDate today=LocalDate.now();LocalDate oldest=today.minusYears(max+1L).plusDays(1),newest=today.minusYears(min);return em.createQuery("select p from SocialEntities$Profile p join p.user x join SocialEntities$Preference pref on pref.userId=p.userId where p.userId<>:u and x.active=true and x.hidden=false and lower(x.email) not like '%@nook.demo' and pref.visible=true and p.onboardingComplete=true and p.birthDate between :oldest and :newest and not exists(select b.id from SocialEntities$Block b where (b.blockerId=:u and b.blockedId=p.userId) or (b.blockerId=p.userId and b.blockedId=:u)) and not exists(select l.id from SocialEntities$CoffeeLike l where l.senderId=:u and l.receiverId=p.userId) and not exists(select ps.id from SocialEntities$UserPass ps where ps.senderId=:u and ps.receiverId=p.userId) order by p.userId",Profile.class).setParameter("u",u).setParameter("oldest",oldest).setParameter("newest",newest).getResultList();}
 public List<Profile> discoverDemo(UUID u){return em.createQuery("select p from SocialEntities$Profile p join p.user x join SocialEntities$Preference pref on pref.userId=p.userId where p.userId<>:u and x.active=true and x.hidden=false and pref.visible=true and p.onboardingComplete=true and lower(x.email) like '%@nook.demo' and not exists(select b.id from SocialEntities$Block b where (b.blockerId=:u and b.blockedId=p.userId) or (b.blockerId=p.userId and b.blockedId=:u)) and not exists(select l.id from SocialEntities$CoffeeLike l where l.senderId=:u and l.receiverId=p.userId) and not exists(select ps.id from SocialEntities$UserPass ps where ps.senderId=:u and ps.receiverId=p.userId) order by p.userId",Profile.class).setParameter("u",u).getResultList();}
 public List<Profile> demoProfiles(UUID u){return em.createQuery("select p from SocialEntities$Profile p join p.user x join SocialEntities$Preference pref on pref.userId=p.userId where p.userId<>:u and x.active=true and x.hidden=false and pref.visible=true and p.onboardingComplete=true and lower(x.email) like '%@nook.demo' and not exists(select b.id from SocialEntities$Block b where (b.blockerId=:u and b.blockedId=p.userId) or (b.blockerId=p.userId and b.blockedId=:u)) order by p.userId",Profile.class).setParameter("u",u).getResultList();}
 public void execute(String jpql,String name,Object value){em.createQuery(jpql).setParameter(name,value).executeUpdate();}
}
